name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install -y protobuf-compiler qemu-utils
    - uses: actions/checkout@v4
      with:
        path: main
    - name: checkout skiff
      uses: actions/checkout@v4
      with:
        repository: jamesseeman/skiff
        path: skiff
    - name: Build
      run: cargo build --verbose
      working-directory: main
    - name: Run tests
      run: cargo test --verbose
      working-directory: main
